### ISSUE TITLE
Combining static pages with React

### ISSUE THREAD

**Issue by timsoraro** [onkolahmet/Keeper-App#1]
Hi! Thanks a lot for this repo, I learned quite a bit.

I am a beginner in developing websites (just finished the Udemy course) so this repo was helpful in tieing everything I learned together. But I'm kinda stuck. I want to create a website where I have my static pages: homepage, contact, pricing, etc.. and when the users log-in they go to a dashboard which is a react app. Do you have an idea of how to achieve this? How do other companies do it in the same domain?

Thanks.

**Comment by onkolahmet** [comment]
Hi there,
As far as i understood, you want to create an admin panel using static components and navigate through them for your  website.  For this purpose you can use react-admin library. You can access the documentation [from here](https://github.com/marmelab/react-admin). They briefly explain how to use it and what it's functionalities are. 

You may also take a look at the articles below.
- [Building an admin console in react-admin.](https://retool.com/blog/building-an-admin-console-in-react-admin/)
- [React-admin tutorial.](https://marmelab.com/react-admin/Tutorial.html)
- [Building an admin panel with React.](https://blog.logrocket.com/admin-panel-with-react/)

**Comment by timsoraro** [comment]
Hi! Thanks for replying.

It's not quite what I meant, I should have better explained myself.
I'm working on a platform website where people can buy or sell a service. I have index.html, pricing.html, contact.html, etc... these are all static pages. But I also want to create 2 dashboards: 1. for buyers to shop for products and 2. for sellers to manage the products they are selling and orders. Both are dynamic pages that I want to create with React. I'm not certain about the best way to create such a website. One way I thought about doing it was by creating userState variable which will decide what component/page to render/return. But I'm not sure if it's the right way as it seems cumbersome. Your help is appreciated. Thanks.

**Comment by onkolahmet** [comment]
I guess, I got your point that time. You want to create e-commerce website both for the customer and the dealer. I haven't worked on creating e-commerce website before but all i know is you can use [Next.js](https://nextjs.org). 

They have a section for this purpose. You can get further information [from here](https://nextjs.org/commerce) and look into [demo version](https://demo.vercel.store) of it.  

Best regards.

**Comment by timsoraro** [comment]
Hmm, it looks complicated. But I'll look into it. Thank you!
